### ISSUE TITLE
Alt Theme Error?

### ISSUE THREAD

**Issue by Dulanic** [hotio/qbittorrent#28]
Just recently, QBT started showing this:

`Unacceptable file type, only regular file is allowed.`

However, I didnt change anything. This is my .env:

docker compose:
```

  qbt:
    cap_add:
      - NET_ADMIN
    container_name: qbt
    dns:
      - 1.1.1.1
    env_file:
      - /home/dulanic/docker/envs/common.env
      - /home/dulanic/docker/envs/qbt.env
    image: ghcr.io/hotio/qbittorrent:release-4.5.5
    ports:
      - '8089:8089'
      - '8118:8118'
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1

```

qbt.env:
```
UMASK=002
VPN_ENABLED=true
VPN_LAN_NETWORK=192.168.2.0/24
VPN_CONF=wg0
WEBUI_PORTS=8089/tcp,8089/udp
PRIVOXY_ENABLED=false
TP_HOTIO=true
TP_THEME=organizr
```
common.env
```
TZ=America/Chicago
PUID=1000
PGID=1000
```
