### ISSUE TITLE
qbittorrent with custom PUID and GUID not setting permissions correctly

### ISSUE THREAD

**Issue by Dialgatrainer02** [hotio/qbittorrent#40]
hello, im using qbittorrent with a custom PUID+GUID as imj also running the rest of the arrstack with the same options however during the first run qbittorrent when its creating the config directory the permsision of the directory /config/config is set incorrectly and i have to manually either +777 the directory or chown it to the correct owner 
my compose file
```
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      PUID: 911
      PGID: 911
      # UMASK: 002
      TZ: Etc/UTC
      PRIVOXY_ENABLED: true
      UNBOUND_ENABLED: false
      WEBUI_PORTS: 8080/tcp,8080/udp
    volumes:
      - ./.config/qbittorrent:/config
      - ./qbittorrent.conf:/config/config/qBittorrent.conf:ro
      - ./mock/torrents:/data
    restart: unless-stopped
    # user: 911:911
    # tmpfs:
      # - /run:exec
    # read_only: true
```

also mildly off topic question but do you know to make the container read only ive tried but i get a bunch of errors and i dont know which dirs to make tmpfs
